# Train cityscapes using Mapillary-pretrained weights
# Requires 32GB GPU
# Adjust nproc_per_node according to how many GPUs you have

CMD: "python -m torch.distributed.launch --nproc_per_node=4 train.py"

HPARAMS: [
  {
   dataset: cityscapes_dark,
   cv: 0,
   syncbn: true,
   apex: true,
   fp16: true,
   crop_size: "1024,1024",
   bs_trn: 1,
   poly_exp: 2,
   lr: 1e-4,
   rmi_loss: true,
   max_epoch: 35,
   n_scales: "0.5,1.0,2.0",
   supervised_mscale_loss_wt: 0.05,
   snapshot: "ASSETS_PATH/seg_weights/blurred_checkpoint_ep33.pth",
   arch: ocrnet.HRNet_Mscale,
   result_dir: LOGDIR,
   RUNX.TAG: '{arch}',
  },
]
